#!/bin/bash
set -e # exit script on error
BASE=`dirname "$(readlink -f "$0")"`
cd $BASE

VERSION=`cat Hjson/Hjson.csproj | sed -rn 's/.*VersionPrefix>(.*)<\/.*/\1/p'`
VERSION2=`cat Hjson/Properties/AssemblyInfo.cs | sed -rn 's/.*AssemblyFileVersion\("(.*).0"\).*/\1/p'`
if [[ "$VERSION" != "$VERSION2" ]]; then echo error: version mismatch $VERSION:$VERSION2; exit; fi

echo ------------------
echo build .net

xbuild /p:Configuration=Release legacy/Hjson.sln

# test
mono legacy/test/bin/Release/Test.exe test/assets

echo ------------------
echo pkg

mkdir -p nuget
nuget pack Hjson.nuspec -Version $VERSION -OutputDirectory nuget/
