[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyDescription("Hjson.dll")]
[assembly: System.Reflection.AssemblyProduct("Hjson - https://github.com/laktak/hjson-cs")]
[assembly: System.Reflection.AssemblyCopyright("See LICENSE")]
[assembly: System.Reflection.AssemblyFileVersion("1.14.4.0")]
[assembly: System.Reflection.AssemblyTitle("Hjson.dll")]
[assembly: System.CLSCompliant(true)]
